version: 2

jobs:
  ghc-8.2.2:
    docker:
      - image: docker:stable-git
    environment:
      - GHC_REV: "ghc-8.2.2-release"
      - GHC_VER: "8.2.2"
      # - GHC_CONF_OPTS: --enable-unregisterised
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u donatello -p $DOCKER_PASS
          docker build --build-arg GHC_REV=$GHC_REV --build-arg GHC_VER=$GHC_VER --build-arg GHC_CONF_OPTS=$GHC_CONF_OPTS -t donatello/meikyu:ghc-8.2.2-stack .
          docker push donatello/meikyu:ghc-8.2.2-stack

workflows:
  version: 2
  build:
    jobs:
      - ghc-8.2.2
